### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by sherKuo** [sherKuo/property-pulse#3]
"TypeError: Cannot read properties of undefined (reading '0')" 

The error seems to be coming from `app > properties > [id] > page.jsx` specifically the `<PropertyHeaderImage>`.  My site breaks whenever I try to open up an individual property page.  

Someone on the forums had also mentioned something similar although I'm not sure if this applies to my problem. 

The images are coming in as empty objects because it had not properly loaded by the time it was needed. The solutions would be to make sure the image upload process is fully executed before sending the data to the route. 

The upload process in question  is in `app > api > properties > route.js > POST function` where we grab the images from the form data, upload them into cloudinary folder (I confirmed that everything I have uploaded is present in my cloudinary folder), save the Cloudinary image link to a buffer and then upload all image links into my DB.

**Comment by PandaGnar** [comment]
Talked through this on a video call.

**Comment by sherKuo** [comment]
This was fixed with the mose recent branch merge
